/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asm_jv3.view;

import Model.SmartPhone;
import Model.view.Stocker;
import Service.QLSPService;
import Service_IMPL.QLSPServiceIMPL;
import Util.Uhelper;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author chung
 */
public class Updateprd extends javax.swing.JFrame {
    
    QLSPService QLSPV = new QLSPServiceIMPL();
    ASM asm;
    private DefaultComboBoxModel cboModel;
    List<SmartPhone> list = new ArrayList<>();

    /**
     * Creates new form Updateprd
     */
    public Updateprd(ASM parent) {
        this.asm = parent;
        initComponents();
        loadCBO(QLSPV.getCBOPM());
        setLocationRelativeTo(null);
    }
    
    private Updateprd() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public void loadCBO(List<SmartPhone> lst) {
        cboModel = (DefaultComboBoxModel) cboUpProductCategoryID.getModel();
        for (SmartPhone sp : lst) {
            cboModel.addElement(sp.getCategoryId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelUpproduct = new javax.swing.JButton();
        lblUpProductTitle = new javax.swing.JLabel();
        lblUpProductCetaID = new javax.swing.JLabel();
        txtUpProductName = new javax.swing.JTextField();
        lblUpProductName = new javax.swing.JLabel();
        cboUpProductCategoryID = new javax.swing.JComboBox<>();
        btnUpProduct = new javax.swing.JButton();
        lblUpProductID = new javax.swing.JLabel();
        txtUpProductID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCancelUpproduct.setText("Cancel");
        btnCancelUpproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelUpproductActionPerformed(evt);
            }
        });

        lblUpProductTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUpProductTitle.setText("Update product");

        lblUpProductCetaID.setText("Category ID");

        lblUpProductName.setText("Name");

        cboUpProductCategoryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUpProductCategoryIDActionPerformed(evt);
            }
        });

        btnUpProduct.setText("Update");
        btnUpProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpProductActionPerformed(evt);
            }
        });

        lblUpProductID.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUpProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUpProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUpProductCetaID)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(cboUpProductCategoryID, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUpProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUpProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpProduct)
                        .addGap(131, 131, 131)
                        .addComponent(btnCancelUpproduct)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUpProductTitle)
                        .addGap(84, 84, 84))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboUpProductCategoryID, txtUpProductID, txtUpProductName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblUpProductCetaID, lblUpProductID, lblUpProductName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUpProductTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpProductCetaID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboUpProductCategoryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpProduct)
                    .addComponent(btnCancelUpproduct))
                .addGap(32, 32, 32))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboUpProductCategoryID, txtUpProductID, txtUpProductName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblUpProductCetaID, lblUpProductID, lblUpProductName});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelUpproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelUpproductActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.setEnabled(false);
    }//GEN-LAST:event_btnCancelUpproductActionPerformed

    private void cboUpProductCategoryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUpProductCategoryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUpProductCategoryIDActionPerformed

    private void btnUpProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpProductActionPerformed
        // TODO add your handling code here:
        int id;
        try {
            id = Integer.parseInt(txtUpProductID.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "id is number");
            return;
        }
        int cateID = (int) cboUpProductCategoryID.getSelectedItem();
        String name = (String) txtUpProductName.getText();
        if (valuesDate()) {
            SmartPhone sp = new SmartPhone(cateID, name);
            JOptionPane.showMessageDialog(this, QLSPV.updatePRD(id, sp));
            asm.loadDataPM(QLSPV.getListPM());
            this.setVisible(false);
            this.setEnabled(false);
        }
    }//GEN-LAST:event_btnUpProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updateprd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updateprd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updateprd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updateprd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updateprd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelUpproduct;
    private javax.swing.JButton btnUpProduct;
    private javax.swing.JComboBox<String> cboUpProductCategoryID;
    private javax.swing.JLabel lblUpProductCetaID;
    private javax.swing.JLabel lblUpProductID;
    private javax.swing.JLabel lblUpProductName;
    private javax.swing.JLabel lblUpProductTitle;
    private javax.swing.JTextField txtUpProductID;
    private javax.swing.JTextField txtUpProductName;
    // End of variables declaration//GEN-END:variables

    public boolean valuesDate() {
        if (Uhelper.CheckNull(txtUpProductID, "id is not empty")) {
            return false;
        }
        if (Uhelper.CheckNull(txtUpProductName, "name is not empty")) {
            return false;
        }
        return true;
    }
    
}
