/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Service.*;
import View_Model.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chung
 */
public class QLSPCT extends javax.swing.JFrame {

    int index = -1;
    DefaultTableModel model = new DefaultTableModel();
    DefaultComboBoxModel CBOModel;
    DAO_DSP svDSP = new DSP_impl();
    DAO_MS svMS = new MS_impl();
    DAO_NSX svNSX = new NSX_impl();
    DAO_SP svSP = new SP_impl();
    DAO_CTSP svr = new CTSP_impl();

    /**
     * Creates new form QLCTSP
     */
    public QLSPCT() {
        initComponents();
        setLocationRelativeTo(this);
        txtid.setEnabled(false);
        loadCBODSP(svDSP.getAllDSP());
        loadCBOMS(svMS.getAllMauSac());
        loadCBONSX(svNSX.getAllNSX());
        loadCBOSP(svSP.getAllSP());
        fillToTable(svr.getAllCTSP());
        cboiddsp.setSelectedIndex(-1);
        cboidsp.setSelectedIndex(-1);
        cboidms.setSelectedIndex(-1);
        cboidnsx.setSelectedIndex(-1);
    }

    public void loadCBOSP(ArrayList<VMSanPham> lstsp) {
        CBOModel = new DefaultComboBoxModel();
        CBOModel = (DefaultComboBoxModel) cboidsp.getModel();
        for (VMSanPham sp : lstsp) {
            CBOModel.addElement(sp.getId());
        }
    }

    public void loadCBODSP(ArrayList<VMDongSP> lstdsp) {
        CBOModel = new DefaultComboBoxModel();
        CBOModel = (DefaultComboBoxModel) cboiddsp.getModel();
        for (VMDongSP dsp : lstdsp) {
            CBOModel.addElement(dsp.getId());
        }
    }

    public void loadCBOMS(ArrayList<VMMauSac> lstms) {
        CBOModel = new DefaultComboBoxModel();
        CBOModel = (DefaultComboBoxModel) cboidms.getModel();
        for (VMMauSac ms : lstms) {
            CBOModel.addElement(ms.getId());
        }
    }

    public void loadCBONSX(ArrayList<VMNSX> lstnsx) {
        CBOModel = new DefaultComboBoxModel();
        CBOModel = (DefaultComboBoxModel) cboidnsx.getModel();
        for (VMNSX nsx : lstnsx) {
            CBOModel.addElement(nsx.getId());
        }
    }

    public void fillToTable(ArrayList<VMChiTietSP> lstctsp) {
        model = (DefaultTableModel) tblctsp.getModel();
        model.setRowCount(0);
        for (VMChiTietSP c : lstctsp) {
            model.addRow(new Object[]{
                c.getId(),
                c.getIdSP(),
                c.getIdNSX(),
                c.getIdMauSac(),
                c.getIdSP(),
                c.getNamBH(),
                c.getMoTa(),
                c.getSoLuongTon(),
                c.getGiaNhap(),
                c.getGiaBan()
            });
        }
    }

    public void clear() {
        txtid.setText("");
        cboiddsp.setSelectedIndex(-1);
        cboidsp.setSelectedIndex(-1);
        cboidms.setSelectedIndex(-1);
        cboidnsx.setSelectedIndex(-1);
        txtnbh.setText("");
        txtmt.setText("");
        txtslt.setText("");
        txtgn.setText("");
        txtgb.setText("");
    }

    public void showIndex() {
        VMChiTietSP c = svr.getAllCTSP().get(index);
        txtid.setText(c.getId());
        cboiddsp.setSelectedItem(c.getIdDongSP());
        cboidsp.setSelectedItem(c.getIdSP());
        cboidms.setSelectedItem(c.getIdMauSac());
        cboidnsx.setSelectedItem(c.getIdNSX());
        txtnbh.setText(c.getNamBH() + "");
        txtmt.setText(c.getMoTa());
        txtslt.setText(c.getSoLuongTon() + "");
        txtgn.setText(c.getGiaNhap() + "");
        txtgb.setText(c.getGiaBan() + "");
        tblctsp.setRowSelectionInterval(index, index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnbh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmt = new javax.swing.JTextField();
        txtslt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtgn = new javax.swing.JTextField();
        txtgb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cboidsp = new javax.swing.JComboBox<>();
        cboidnsx = new javax.swing.JComboBox<>();
        cboiddsp = new javax.swing.JComboBox<>();
        cboidms = new javax.swing.JComboBox<>();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblctsp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quan ly chi tiet san pham");

        jLabel2.setText("id");

        jLabel3.setText("nam BH");

        jLabel4.setText("id san pham");

        jLabel5.setText("idNSX");

        jLabel6.setText("id mau sac");

        jLabel7.setText("id dong sp");

        jLabel8.setText("mo ta");

        jLabel9.setText("so luong ton");

        jLabel10.setText("gia nhap");

        jLabel11.setText("gia ban");

        btnthem.setText("them");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("sua");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("xoa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        tblctsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "id sp", "id nsx", "id mau sac", "id dong sp", "nam bh ", "mo ta", "so luong ton", "gia nhap", "gia ban"
            }
        ));
        tblctsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblctspMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblctsp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboidsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboidms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtgn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnthem)
                                                .addGap(96, 96, 96)
                                                .addComponent(btnsua))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtmt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtnbh, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtslt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnxoa)
                                    .addComponent(txtgb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(cboidnsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboiddsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(151, 151, 151))
                    .addComponent(jScrollPane1)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboiddsp, cboidms, cboidnsx, cboidsp, txtgb, txtgn, txtid, txtmt, txtnbh, txtslt});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel3, jLabel5, jLabel7, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel2, jLabel4, jLabel6, jLabel8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnbh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboidsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboidnsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboiddsp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboidms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtslt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnsua, btnthem, btnxoa, cboidms, cboidnsx, cboidsp, jLabel10, jLabel11, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, txtgb, txtgn, txtid, txtmt, txtnbh, txtslt});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblctspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblctspMouseClicked
        // TODO add your handling code here:
        index = tblctsp.getSelectedRow();
        showIndex();
    }//GEN-LAST:event_tblctspMouseClicked
    String iddsp, sp, nsx, ms;
    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (cboiddsp.getSelectedItem() == null) {
            iddsp = null;
        } else {
            iddsp = cboiddsp.getSelectedItem() + "";
        }
        if (cboidnsx.getSelectedItem() == null) {
            nsx = null;
        } else {
            nsx = cboidnsx.getSelectedItem() + "";
        }
        if (cboidms.getSelectedItem() == null) {
            ms = null;

        } else {
            ms = cboidms.getSelectedItem() + "";
        }
        if (cboidsp.getSelectedItem() == null) {
            sp = null;

        } else {
            sp = cboidsp.getSelectedItem() + "";
        }
        int nbh = Integer.parseInt(txtnbh.getText());
        String mt = txtmt.getText();
        int slt = Integer.parseInt(txtslt.getText());
        double gn = Double.parseDouble(txtgn.getText());
        double gb = Double.parseDouble(txtgb.getText());
        VMChiTietSP c = new VMChiTietSP(sp, nsx, ms, iddsp, nbh, mt, slt, gn, gb);
        JOptionPane.showMessageDialog(this, svr.addNewCTSP(c));
        clear();
        fillToTable(svr.getAllCTSP());
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
try {
                    String id = svr.getAllCTSP().get(index).getId();
        if (cboiddsp.getSelectedItem() == null) {
            iddsp = null;
        } else {
            iddsp = cboiddsp.getSelectedItem() + "";
        }
        if (cboidnsx.getSelectedItem() == null) {
            nsx = null;
        } else {
            nsx = cboidnsx.getSelectedItem() + "";
        }
        if (cboidms.getSelectedItem() == null) {
            ms = null;

        } else {
            ms = cboidms.getSelectedItem() + "";
        }
        if (cboidsp.getSelectedItem() == null) {
            sp = null;

        } else {
            sp = cboidsp.getSelectedItem() + "";
        }
        int nbh = Integer.parseInt(txtnbh.getText());
        String mt = txtmt.getText();
        int slt = Integer.parseInt(txtslt.getText());
        double gn = Double.parseDouble(txtgn.getText());
        double gb = Double.parseDouble(txtgb.getText());
        VMChiTietSP c = new VMChiTietSP(sp, nsx, ms, iddsp, nbh, mt, slt, gn, gb);
        JOptionPane.showMessageDialog(this, svr.UpdateCTSP(id, c));
        index = 0;
        clear();
        fillToTable(svr.getAllCTSP());
        tblctsp.setRowSelectionInterval(index, index);
        } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "chon CTSP muon sua");
            return;
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        try {
             String id = svr.getAllCTSP().get(index).getId();
              JOptionPane.showMessageDialog(this, svr.DeleteCTSP(id));
        index = 0;
        clear();
        fillToTable(svr.getAllCTSP());
        tblctsp.setRowSelectionInterval(index, index);
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "chon CTSP muon xoa");
            return;
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSPCT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cboiddsp;
    private javax.swing.JComboBox<String> cboidms;
    private javax.swing.JComboBox<String> cboidnsx;
    private javax.swing.JComboBox<String> cboidsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblctsp;
    private javax.swing.JTextField txtgb;
    private javax.swing.JTextField txtgn;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmt;
    private javax.swing.JTextField txtnbh;
    private javax.swing.JTextField txtslt;
    // End of variables declaration//GEN-END:variables
}
